### ISSUE TITLE
[MPI_WP2]: 5. OsteoBioR - Option to export values for displayed graph

### ISSUE THREAD

**Issue by jroachell15** [Pandora-IsoMemo/osteo-bior#11]
- [ ] Option to export values for displayed graph under “Credibility intervals over time” (mean and selected interval range). For data gaps include x values but leave y blank. For the x axis values include three separate columns (low/high range values plus their media).
- [ ]  Option to export data for single plots or batch export. For the latter a single file is generated with data for different individuals separated by a fully empty row. Individual ID’s are given in a first column and for all x values.

Above only after completion of:
- https://github.com/Pandora-IsoMemo/osteo-bior/issues/3

See also:
- https://github.com/Pandora-IsoMemo/osteo-bior/issues/2

**Comment by arunge** [comment]
Will be solved within 
- https://github.com/Pandora-IsoMemo/osteo-bior/issues/43
