### ISSUE TITLE
Bug with summary results

### ISSUE THREAD

**Issue by CarloCocozza** [Pandora-IsoMemo/osteo-bior#12]
For the attached mode (which actually is the example model) in OsteoBioR, when trying to export "interval data" in the "summary" section, only a number appears in the excel file (attached). This has nothing to do with the summary that is shown in the interface.

Also, the summary reports three intervals, whereas in the plot (attached) only two are shown. Moreover, "interval [1]", "interval [2]", and "interval [3]" do not specify the number in the time line. 

@arunge 

![20220911_Credibility_Intervals_Over_Time](https://user-images.githubusercontent.com/101706974/189541819-9b54d0aa-e66c-430c-a852-faa8d1f50f98.png)
[2022-09-11_19_24_05_OsteoBioR.zip](https://github.com/Pandora-IsoMemo/osteo-bior/files/9543198/2022-09-11_19_24_05_OsteoBioR.zip)
[isotopeData.xlsx](https://github.com/Pandora-IsoMemo/osteo-bior/files/9543199/isotopeData.xlsx)

**Comment by arunge** [comment]
@CarloCocozza I pushed a new [version 22.11.1](https://github.com/Pandora-IsoMemo/osteo-bior/pull/13#issue-1449842557) to the [beta app](https://isomemoapp.com/app/osteo-bio-r-beta).

This should fix the issues mentioned above. The version should be available after it passed all automatic checks. Please, let me know if you find another issue. Thanks for your patience!

**Comment by arunge** [comment]
@CarloCocozza The [new version](https://isomemoapp.com/app/osteo-bio-r-beta) is online for a while now. Had you time to test the fix?

**Comment by arunge** [comment]
Closing here since nothing was reported for a while. Please feel free to open another issue in case of trouble.
