### ISSUE TITLE
Bug: File import leads to crash

### ISSUE THREAD

**Issue by arunge** [Pandora-IsoMemo/osteo-bior#19]
While trying to merge the new feature for _renewal rates uncertainties_ into the beta version, I found that on the main app the file import seems to be corrupt. When uploading a file for the renewal rates the app crashes:

![image](https://user-images.githubusercontent.com/16759098/225308902-8a769a6f-99f7-4438-a7dc-717baa793caa.png)

Debugging shows, the following line leads to the error: 
https://github.com/Pandora-IsoMemo/osteo-bior/blob/e11821da0f1ddc2feb9d9fcafa61f8ab2277fdde/inst/app/server.R#L71

@mgross Could you please implement a fix for this? Thanks in advance!

**Comment by mgross** [comment]
@arunge I implemented a fix for this: 
https://github.com/Pandora-IsoMemo/osteo-bior/pull/20
