### ISSUE TITLE
[MPI_2022] OsteoBioR: New UI Input to define the gaps for the labels

### ISSUE THREAD

**Issue by jroachell15** [Pandora-IsoMemo/osteo-bior#2]
Original ticket: https://github.com/INWT/mpi-temporal-iso/issues/26

...
Regarding:
> Maybe it is enough if one can see the original labels in the plot...

Ricardo is satisfied with the labels. Still, it remains the issue of having gaps (labels) at the beginning or at the end of the time data. We discussed the option to have a third table as input for gaps. That is, the gap table would only affect the labels not the model itself. 

- [ ] I will check, how to implement this in a most simple way.

_Originally posted by @arunge in https://github.com/INWT/mpi-temporal-iso/issues/18#issuecomment-1008884401_

- [x] ask whether to track this also within the support contract

**January 23 update:** 
Ricardo would like to keep the time for the support contract. He asked for collecting all _new tasks_. If we have enough new tasks he would prefer to make a new contract with new time estimates for such tasks.

For now, we leave this task open until other open tasks are done that already belong to an existing contract.

**Comment by arunge** [comment]
Regarding:

> Ricardo is satisfied with the labels. Still, it remains the issue of having gaps (labels) at the beginning or at the end of the time data. We discussed the option to have a third table as input for gaps. That is, the gap table would only affect the labels not the model itself.

This was already solved within: 
- https://github.com/Pandora-IsoMemo/osteo-bior/issues/26
