### ISSUE TITLE
[MPI_2022] OsteoBioR: Table output of data for the derivate plot 

### ISSUE THREAD

**Issue by jroachell15** [Pandora-IsoMemo/osteo-bior#3]
Original Ticket: https://github.com/INWT/mpi-temporal-iso/issues/25

Regarding:
> We would need to refactor the code a bit. Currently, plot data is derived from the model data inside a function, but not in the server function where the plot is generated. I would need to extract the preprocessing of the data for the plot in order to create the table output.

Ricardo would still like to have this output. He asked to check whether output as a table was in the original specifications.

- [x] I checked. It was not mentioned explicitly. 
- ~Therefore, the output of a table will be part of the support contract. ~
- [x] This I will validate with Ricardo in the next meeting, see [below](https://github.com/INWT/mpi-temporal-iso/issues/25#issuecomment-1020030697)
- [ ] implement the new output

...
_Originally posted by @arunge in https://github.com/INWT/mpi-temporal-iso/issues/18#issuecomment-1008884401_

see https://github.com/INWT/mpi-temporal-iso/issues/26#issuecomment-1020028852

> Ricardo would like to keep the time for the support contract. He asked for collecting all new tasks. If we have enough new tasks he would prefer to make a new contract with new time estimates for such tasks.
> 
> For now, we leave this task open until other open tasks are done that already belong to an existing contract.

**Comment by arunge** [comment]
Will be solved within
- https://github.com/Pandora-IsoMemo/osteo-bior/issues/43
