### ISSUE TITLE
Possible memory management in online models

### ISSUE THREAD

**Issue by CarloCocozza** [Pandora-IsoMemo/osteo-bior#38]
When I run a model online, it usually takes some minutes to generate estimates. However, when I run a second model, this takes far longer. If instead I stop and restart the app, even for the second model it takes a few minutes. 
Could it be a problem of memory management of the server?

@arunge

**Comment by arunge** [comment]
This is most likely due to random effects of Bayesian modelling. Please, check the comments regarding several test runs online and locally, here:
- https://github.com/Pandora-IsoMemo/osteo-bior/issues/37#issuecomment-1850324415
