### ISSUE TITLE
[MPI_erweiterung_priority_047]: OsteoBioR: batch option to run several models: the user can upload a single files (7 days)

### ISSUE THREAD

**Issue by jroachell15** [Pandora-IsoMemo/osteo-bior#4]
original ticket: https://github.com/INWT/mpi-temporal-iso/issues/18

Task no. 7 from (old new tasks). also related to #17 

OsteoBioR: batch option to run several models: the user can upload a single files for “Renewal rates dataset”, “ Mean and (optional) standard deviation of measurements”, and “Model specification” (Time variables and Element variables). These files will contain entries for different individuals each identified by column entry with a common name. Number of columns/rows for each individual may vary and the first row for each individual identifies the column names. Example:

## “Renewal rates dataset” (the Mean table follows a similar approach)

A intStart intend bone1 bone2 tooth1 tooth2
A 0 1 100 100 0 0
A 0 2 50 100 0 0 
B intStart intend bone1 bone2 tooth1 tooth2 tooth3
B 0 1 100 100 0 0 0 
B 1 2 50 100 0 0 0
C Start End bone1 bone2 tooth1 
C 0 1 100 100 0 
C 1 2 50 100 0 
C 2 3 20 5 0 

“Model specification” (time variables)
A intStart intend
B intStart intend
C start end
“Model specification” (Element variables)
A intStart intend bone1 bone2 tooth1 tooth2 
B intStart intend bone1 bone2 tooth1 tooth2 tooth3
C intStart intend bone1 bone2 tooth1 

- [ ] In the output, the user will have a pending list option to select for which individual to show the results presently available. There should be also a batch export option where current table outputs are combined in a single file and graphical outputs in a zipped file containing the separate image files. 

- [x] For “Shift detection” add an optional criterion to identify shifts: a minimum (mean) slope value between the points detected (negative slopes are converted into a positive value) by the absolute or relative criteria.   

- [x] Add batch estimate options for “Shift detection”, “Time point estimates”. The first column in the estimate table identifies the individual.

- [x] Some intervals may be defined as gaps (mid or end of sequence) in the “Renewal rates dataset”. For these there will be no isotopic measurement given and as such do not interfere in estimates. Furthermore, these gaps may or not be displayed in outputs as gap depending on user selection.

## Additional estimates (also relevant for batch options):

- [x] calculating average+SD following an estimate for a user-selected range of intervals

- [x] calculating total turnover across a range of intervals

- [x] derivative graph for current graph “Credibility intervals over time”. The interface should look the same as for “Credibility intervals over time”.

**Comment by arunge** [comment]
Almost everything done here, the left can be found here: https://github.com/Pandora-IsoMemo/osteo-bior/issues/2
