### ISSUE TITLE
Error in Build Pipeline

### ISSUE THREAD

**Issue by wahani** [Pandora-IsoMemo/osteo-bior#5]
@arunge just to follow protocol and we don't miss it: we still have an error in the build pipeline. 

- Jenkins Job: https://isomemodb.com/jenkins/job/Pandora-IsoMemo/job/osteo-bior/job/beta/4/console

Looks like an issue with the new versioning:

```
Running the tests in ‘tests/testthat.R’ failed.
Last 13 lines of output:
  > library(testthat)
  > library(OsteoBioR)
  Loading required package: Rcpp
  > 
  > test_check("OsteoBioR")
  ══ Failed tests ════════════════════════════════════════════════════════════════
  ── Failure (test-downAndUploadModel.R:2:3): addPackageVersionNo ────────────────
  substr(addPackageVersionNo("abc"), 1, 25) (`actual`) not equal to "abc\n\nOsteoBioR version 22." (`expected`).
  
  `lines(actual)`:   "abc" "" "OsteoBioR version 22" 
  `lines(expected)`: "abc" "" "OsteoBioR version 22."
  
  [ FAIL 1 | WARN 0 | SKIP 0 | PASS 27 ]
  Error: Test failures
  Execution halted
```

**Comment by arunge** [comment]
Fixed:

![image](https://user-images.githubusercontent.com/16759098/155982835-e726ae2f-c92d-4d5b-8401-46952216b192.png)

![image](https://user-images.githubusercontent.com/16759098/155982903-dc1e96c0-a83c-4af4-a0f3-346ae94e8832.png)
